server:
  port: 19999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 配置路径
      routes:
        - id: auth-server
          # 转发uri
          uri: http://127.0.0.1:20002/
          #  断言配置
          predicates:
            # path断言
            - Path=/auth/**

