eureka:
  instance:
    # 指定服务治理中心服务器ip
    hostname: 192.168.0.88
  client:
    # 取消注册，服务自己是治理中心，开发环境取消注册
    register-with-eureka: false
    # 取消服务获取
    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation:  false

server:
  # 指定端口
  port: 20000
  # 业务名字
  servlet:
    context-path: /register

spring:
  application:
    # 配置微服务名称
    name: registter-server
