spring:
  application:
    name: wechat-server

server:
  # 指定端口在20001
  port: 20001

eureka:
  instance:
    hostname: 192.168.0.88
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.88:20000/eureka