spring:
  application:
    name: wechat-server

server:
  port: 20010

eureka:
  instance:
    hostname: 192.168.0.176
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.176:20000/eureka/,http://192.168.0.176:20001/eureka/